#spring:
#  application:
#    name: api-gatway
#  cloud:
#    gateway:
#      routes:
#        - id: AdminService
#          uri: http://localhost:8084/
#               predicates:
#                  -Path=/admin/**
#        - id: ProductService
#          uri: http://localhost:8092/
##        predicates=
##          - path=/product/**
#
#
#



server:
  port: 8080